Update CircleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,14 +6,46 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Install AWS CLI, jq and npm
+          name: Install AWS CLI
+          command: |
+            if which aws > /dev/null; then
+              echo "The AWS CLI is already installed. Skipping."
+              exit 0
+            fi
+
+            export PIP=$(which pip pip3 | head -1)
+            if [[ -n $PIP ]]; then
+              if which sudo > /dev/null; then
+                sudo $PIP install awscli --upgrade
+              else
+                # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+                $PIP install awscli --upgrade --user
+              fi
+            elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+              cd
+              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+              unzip awscli-bundle.zip
+              if which sudo > /dev/null; then
+                sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+              else
+                # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+                awscli-bundle/install -b ~/bin/aws
+              fi
+              rm -rf awscli-bundle*
+              cd -
+            else
+              echo "Unable to install AWS CLI. Please install pip."
+              exit 1
+            fi
+      - run:
+          name: Install jq and npm
           command: |
             sudo apt-get update
             sudo apt-get install -y jq zip python3-pip
             pip3 install awscli --upgrade
             curl -sL https://deb.nodesource.com/setup_8.x | bash -
             sudo apt-get install -y nodejs
-            npm install -g npm@5
+            npm install -g npm
             aws configure set default.region $AWS_REGION
       - run:
           name: Install dependencies
